version: '3.8'

services:
  postgres:
    image: postgres:16.3-alpine
    container_name: ticket-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ticket_db
    networks:
      - ticket-monster-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d ticket_db" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.0
    container_name: ticket-zk
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - ticket-monster-network

  kafka:
    image: confluentinc/cp-kafka:7.7.0
    depends_on:
      - zookeeper
    container_name: ticket-kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://ticket-kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    volumes:
      - ./kafka-data:/var/lib/kafka/data
    networks:
      - ticket-monster-network
    healthcheck:
      test: [ "CMD-SHELL", "kafka-broker-api-versions --bootstrap-server ticket-kafka:9092 | grep -q 'id:1'" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  ticket-service:
    build:
      dockerfile: Dockerfile-dev
    container_name: ticket-service-1
    image: ticket-service-dev
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ticket-db:5432/ticket_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_APP_PORT: 8080
      KAFKA_BOOTSTRAP_SERVERS: ticket-kafka:9092
      ACTIVE_PROFILES_PROPERTY_NAME: production
      SPRING_PROFILES_ACTIVE: production
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/opt/app
      - ~/.m2:/root/.m2
      - ./target:/opt/app/target
    depends_on:
      kafka:
        condition: service_started
    networks:
      - ticket-monster-network
    command: ./mvnw spring-boot:run

networks:
  ticket-monster-network:
    driver: bridge