server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

spring:
  mvc:
    static-path-pattern: /**
  application:
    name: ticket-monster

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH_REGISTRATION_ID}
            client-secret: ${GOOGLE_OAUTH_REGISTRATION_SECRET}
            redirect-uri: "http://localhost:8080/oauth2/callback/google-pkce"
        provider:
          google:
            token-uri: https://oauth2.googleapis.com/token
            authorization-uri: https://accounts.google.com/o/oauth2/auth

  kafka:
    bootstrap-servers: localhost:9092

  datasource:
    url: jdbc:postgresql://localhost:5432/ticket_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.flywaydb: DEBUG

whitelist:
  requestMatchers:
    GET:
      - /tickets/**
    POST:
      - /auth/**
